"""Resize the supplied brand artwork into every icon the app needs.

    python3 tool/brand_assets.py

This script does not draw anything. Every pixel it writes comes from one
of the three masters in brand/ - it only crops, scales and pads them, so
the icons can be rebuilt the day the artwork changes without anybody
redrawing them by hand.

    brand/icon_navy.png        the mark on the navy card, full bleed
    brand/mark_light.png       the mark in white and green, transparent
    brand/logo_full_navy.png   the whole logo in navy, transparent
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / 'brand'

# The brand palette, as the brand sheet states it.
BRAND_NAVY = (0x0D, 0x2B, 0x49)
BRAND_GREEN = (0x14, 0xD1, 0xA0)
SPLASH_BACKGROUND = '#F2F5F9'

# Where the illustration ends and the wordmark begins in the full logo -
# measured off the artwork's own alpha, not guessed.
MARK_ENDS_AT = 0.667

# An adaptive icon is 108dp but only the middle 72dp survives whatever
# mask the launcher applies, and the artwork wants a little air inside
# even that.
ADAPTIVE_SAFE = 72 / 108
ADAPTIVE_FILL = 0.86

DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}


def trimmed(image):
    box = image.getbbox()
    return image.crop(box) if box else image


def padded(art, size, coverage):
    """The artwork centred on a transparent square of [size], taking up
    [coverage] of it."""
    art = trimmed(art)
    scale = min(size * coverage / art.width, size * coverage / art.height)
    art = art.resize((max(1, round(art.width * scale)),
                      max(1, round(art.height * scale))), Image.LANCZOS)
    canvas = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(art, ((size - art.width) // 2,
                                 (size - art.height) // 2))
    return canvas


def main():
    icon_navy = Image.open(BRAND / 'icon_navy.png').convert('RGB')
    mark_light = Image.open(BRAND / 'mark_light.png').convert('RGBA')
    logo_full = Image.open(BRAND / 'logo_full_navy.png').convert('RGBA')

    # The navy mark on its own, taken from the top of the full logo.
    mark_navy = logo_full.crop((0, 0, logo_full.width,
                                round(logo_full.height * MARK_ENDS_AT)))

    # 1. The logo the app itself shows, on the splash and the login.
    (ROOT / 'assets' / 'images').mkdir(parents=True, exist_ok=True)
    logo_full.save(ROOT / 'assets' / 'images' / 'app_logo.png')

    res = ROOT / 'android' / 'app' / 'src' / 'main' / 'res'
    for name, factor in DENSITIES.items():
        folder = res / f'mipmap-{name}'
        folder.mkdir(parents=True, exist_ok=True)

        # Android 7 and older draw this bitmap as the launcher icon.
        legacy = round(48 * factor)
        icon_navy.resize((legacy, legacy), Image.LANCZOS).save(
            folder / 'ic_launcher.png')

        # Android 8+ composes its own: white mark over a navy background.
        adaptive = round(108 * factor)
        padded(mark_light, adaptive, ADAPTIVE_SAFE * ADAPTIVE_FILL).save(
            folder / 'ic_launcher_foreground.png')

        # The Android 12 splash paints its icon on a light background,
        # where the white mark would be invisible - so that one is navy.
        padded(mark_navy, adaptive, ADAPTIVE_SAFE * ADAPTIVE_FILL).save(
            folder / 'ic_splash_foreground.png')

    (res / 'mipmap-anydpi-v26').mkdir(parents=True, exist_ok=True)
    (res / 'mipmap-anydpi-v26' / 'ic_launcher.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/brand_assets.py -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/brand_navy"/>\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>\n'
        '    <monochrome android:drawable="@mipmap/ic_launcher_foreground"/>\n'
        '</adaptive-icon>\n')

    (res / 'values').mkdir(parents=True, exist_ok=True)
    (res / 'values' / 'colors.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/brand_assets.py -->\n'
        '<resources>\n'
        '    <color name="brand_navy">#%02X%02X%02X</color>\n'
        '    <color name="brand_green">#%02X%02X%02X</color>\n'
        '    <color name="brand_splash">%s</color>\n'
        '</resources>\n' % (BRAND_NAVY + BRAND_GREEN + (SPLASH_BACKGROUND,)))

    # 2. The web build. The card already bleeds to its edges, which is
    #    exactly what a maskable icon needs.
    web = ROOT / 'web'
    icon_navy.resize((512, 512), Image.LANCZOS).save(web / 'favicon.png')
    (web / 'icons').mkdir(parents=True, exist_ok=True)
    for px in (192, 512):
        small = icon_navy.resize((px, px), Image.LANCZOS)
        small.save(web / 'icons' / f'Icon-{px}.png')
        small.save(web / 'icons' / f'Icon-maskable-{px}.png')

    # 3. What gets uploaded to Play Console by hand.
    store = BRAND / 'store'
    store.mkdir(exist_ok=True)
    icon_navy.resize((512, 512), Image.LANCZOS).save(store / 'play_icon_512.png')

    print('done')


if __name__ == '__main__':
    main()
